//
//  Functions13.swift
//  LearningSwiftApp
//
//  Created by Thore Brehmer on 12.08.23.
//

import SwiftUI

//takeaway:
//1. structs are similar to classes
//2. they have an "autogenerated" initialiser, but it can be be customised
struct Constructor13: View {
    var body: some View {
        HStack {
            Constructor_Test(fruit: .Apple, count: 100)
            Constructor_Test(fruit: .Orange, count: 46)
        }
    }
}

struct Constructor_Test: View {
    //parameters
    let fruit: Fruit
    let count: Int
    let name: String
    let color: Color
    
    //variables
    
    //"constructor"
    /// optional: for normal paras is autogenerated
    init(fruit: Fruit, count: Int) {
        self.fruit = fruit
        self.count = count
        
        if fruit == Fruit.Apple{
            self.name = "Apple"
            self.color = .red
        }
        else{
            self.name = "Orange"
            self.color = .orange
        }
    }
    
    var body: some View{
        VStack {
            Text("\(self.count)")
                .font(.largeTitle)
                .underline()
                .foregroundColor(.white)
                .padding(.bottom, 8)
            
            Text("\(self.name)")
                .font(.headline)
                .foregroundColor(.white)
        }
        
        .frame(width: 150, height: 150)
        .background(self.color)
        .cornerRadius(20)
        
    }
}

enum Fruit {
    case Apple
    case Orange
}


struct Constructor13_Previews: PreviewProvider {
    static var previews: some View {
        Constructor13().previewDevice(PreviewDevice(rawValue: "iPhone 14 Pro Max"))
    }
}
